baseURL = "https://rlplaybook.com"
languageCode = "en-us"
title = "Reinforcement Learning Playbook"
theme = "timeline"

[Params]
author = "Shehab Yasser"
authorURL = "https://www.shehabyasser.com"
video = "DQN Breakout.mp4"
header = "RL Playbook"
timelineTitle = "How RL Evolved"

[markup.goldmark.renderer]
unsafe= true